language: node_js
node_js:
  - '10.0'

dist: trusty
sudo: false

script:
  - yarn run build

after_success:
  - git config --global user.name "Travis CI"
  - git config --global user.email "travis@j3tto.com"
  - git remote rm origin
  - git remote add origin https://${GITHUB_TOKEN}@github.com/J3tto/chesswithtony.git
deploy:
- provider: script
  skip_cleanup: true
  script: yarn run deploy
  on:
    branch: master
